### ISSUE TITLE
Add an in-app browser (Using WKWebView)

### ISSUE THREAD

**Issue by pcgamer31098** [ProtonMail/ios-mail#15]
**Is your feature request related to a problem? Please describe.**
There should be an option to have an in-app browser in the ProtonMail app so you can quickly view and exit from a website within the app.

**Describe the solution you'd like**
You can use the WKWebView API to accomplish this.

**Describe alternatives you've considered**
I don't have any alternatives.

**Additional context**
I don't have any additional information.

**Comment by abjurato** [comment]
This is implemented by @mackuba here:
https://github.com/ProtonMail/ios-mail/pull/8

**Comment by abjurato** [comment]
Update: released in v1.11.14
