### ISSUE TITLE
Android App Open Source

### ISSUE THREAD

**Issue by fkirc** [ProtonMail/ios-mail#17]
I have not yet seen a repo for the Android ProtonMail app. Do you plan to opensource the Android app in the near future?

I am not saying that you need to use the GNU license, but it would be nice to have the code available, even without any real opensource license.

**Comment by bartbutler** [comment]
We do plan to and will. We are open sourcing all of our clients with a timeline determined by team workload and scheduling, but it should be in early 2020.
