### ISSUE TITLE
URL Scheme for opening mailto: links

### ISSUE THREAD

**Issue by caass** [ProtonMail/ios-mail#30]
**Is your feature request related to a problem? Please describe.**
I'd like to use ProtonMail as my default mail application -- it's my primary email account, and it's inconvenient for me to have to open a `mailto:` link in Apple Mail, and then copy the address over to ProtonMail.

**Describe the solution you'd like**
A description of the URL scheme ProtonMail uses in order to leverage [Evil Scheme](https://repo.dynastic.co/package/evilscheme) ([source](https://github.com/lorenzopane/evilscheme)) to correctly route `mailto:` links to the ProtonMail application.

**Describe alternatives you've considered**
Adapting the [url described here](https://github.com/Noitidart/MailtoWebmails/issues/39#issuecomment-204913510) to `protonmail://secure/start?action=compose&to=`.

**Additional context**
Evil Scheme is a tweak for jailbroken iPhones that allows the "replacement" of default apps by hijacking the url scheme system, and using regular expressions to capture the relevant information and pass them along. For example, configuration for replacing Apple Mail with GMail is:

|   | Source  | Target |
|---|---|---|
| Bundle ID  | com.apple.mobilemail  | com.google.GMail  |
|  Regex | ^mailto:**[^?]\*$**  | googlegmail://co?to=**{capture group}**  |
|  Regex | ^mailto:**.\***?**.\*$**  | googlegmail://co?to=**{group 1}**&**{group 2}**  |

So some translations would look like (with the @ removed to kill GitHub's hyperlinking):

mailto:**hey[at]cass.love**   =>  googlemail://co?to=**hey[at]cass.love**
mailto:**hey[at]cass.love**?**subject=Hey!**  => googlemail://co?to=**hey[at]cass.love**&**subject=Hey!**

I'd like to understand what (if it exists) the URL scheme is for generating a new email in ProtonMail is. I thought there might be one because of the "Compose" action when long pressing the icon. Essentially, my target is to fill in the missing information here:

|   | Source  | Target |
|---|---|---|
| Bundle ID  | com.apple.mobilemail  | ch.protonmail.protonmail  |
|  Regex | ^mailto:**[^?]\*$**  | ???**{capture group}**  |
|  Regex | ^mailto:.**\*?.\*$**  | ???**{group 1}**&**{group 2}**  |

Let me know if this is not the right place to submit this, and I'll gladly nose around elsewhere. Thank you for your time!

**Comment by five2seven** [comment]
I’ve been looking everywhere for this! Thank you for asking. Following in hopes of an answer.

**Comment by caassandra** [comment]
I think it's worth bumping with the news that [iOS 14 will allow for selecting a default email client](https://www.theverge.com/2020/6/22/21299342/apple-ipados14-default-apps-email-browser-choice-features-wwdc-2020). Relevant section below:

> Apple didn’t detail this change fully during its keynote, but a section of the iOS 14 preview page says you can “set a default web browser and email app that launch when you click a link or want to compose a new mail message.” The company confirmed to The Verge that developers will have to update their apps in order to support the feature.

If there are plans for ProtonMail to support that, I think it's worth closing this issue and mentioning that the functionality will be available in iOS 14.
