### ISSUE TITLE
Compose email recepient field constantly scans clipboard

### ISSUE THREAD

**Issue by what-name** [ProtonMail/ios-mail#31]
With the new iOS 14 update, the banner that "ProtonMail pasted from the clipboard" appears at every keystroke while typing in a recepient email adress.

I understand that it is normal behaviour to automatically paste from clipboard but I would rather not have this feature, especially not in its current form.

This behaviour does not exist anywhere in the app as far as I have seen, and nowhere outside of the recipient field while composing a new message.

**Comment by zhj4478** [comment]
the duplicate issue we will track this issue in #33
