### ISSUE TITLE
Protonmail grabs paste buffer on entering an address in compose mode

### ISSUE THREAD

**Issue by lazzurs** [ProtonMail/ios-mail#33]
**Describe the bug:**
ProtonMail grabs the current paste buffer when trying to enter an email address in compose mode.

**Live App Version:**
AppVersion: 1.11.17
LibVersion: 1.0.5

**Device + OS version**
iPhone 11 Pro
iOS 14 beta 2

**Can you reproduce the problem each time?**
Yes

**Steps to reproduce the behavior:**
1. Put something into the paste buffer
2. Open ProtonMail
3. Compose a message
4. Enter anything in the To: field
5. Paste buffer is grabbed

**Expected behavior**
The paste buffer only being read as an address is pasted and not before.

**Screenshots**
![image](https://user-images.githubusercontent.com/15793/87589011-7e29e100-c6dc-11ea-8a4c-9ec61b027ac0.png)

**Comment by zhj4478** [comment]
we have fixed it. the beta will be out soon v1.12.1

**Comment by lazzurs** [comment]
Confirmed as no longer happening.
