### ISSUE TITLE
Offer ability to be default Mail app

### ISSUE THREAD

**Issue by lazzurs** [ProtonMail/ios-mail#38]
The new iOS 14 release allows the setting of a default Mail app. ProtonMail iOS does not currently support this feature but it would be great to have.

**Comment by timharek** [comment]
According to their subreddit, they have submitted an request to Apple and is still waiting for approval;

https://old.reddit.com/r/ProtonMail/comments/iu1gmc/protonmail_as_default_in_ios14/g5kpjd3/

**Comment by derekmorr** [comment]
As of at least 1.13.1 ProtonMail can be made the default mail app, so this issue can be closed.
