### ISSUE TITLE
Remove iOS unread notifications if read on another device

### ISSUE THREAD

**Issue by SoMuchToGrok** [ProtonMail/ios-mail#45]
**Is your feature request related to a problem? Please describe.**

When using the iOS app in tandem with another client (i.e. browser), I effectively need to manage 2 independent sets of notifications. After having read an email on my desktop, the iOS notification persists until I manually swipe it away. 

This is an inconvenience that often results in me thinking I have an unread email, despite having already read the email on my desktop. This user experience isn't ideal, and at times it feels like all I'm doing is swiping notifications away on my iPhone.

**Describe the solution you'd like**

Unread email notifications should be cleared from iOS devices when users view an unread email on a non-iOS app client. The system doesn't need to be incredibly real-time. In other words, some element of removal lag can be tolerated (in my opinion).

**Describe alternatives you've considered**

The only temporary workaround I've considered is disabling iOS notifications entirely. This is obviously a heavy hammer approach, but it effectively stops the bleed. 

**Additional context**

* Android app has a similar request - https://github.com/ProtonMail/proton-mail-android/issues/13
* iOS developer docs - [user notifications](https://developer.apple.com/documentation/usernotifications)
* [Implementing removable remote notifications on iOS](https://medium.com/@sebastianosiski/implementing-removable-remote-notifications-on-ios-a17d74832bde)

**Comment by sith-on-mars** [comment]
Hi! Is there any update on this?

**Comment by derfurkan** [comment]
Hi! Is there any update on this?

**Comment by derfurkan** [comment]
Hi! Is there any update on this?

**Comment by derfurkan** [comment]
Hi Is there any update on this?

**Comment by derfurkan** [comment]
Hi im wondering if there are any updates on this?

**Comment by derfurkan** [comment]
Hi im still wondering if there are any updates on this?

**Comment by derfurkan** [comment]
Hi so how is it looking?

**Comment by derfurkan** [comment]
Hi i was wondering if they are still some people interested in this feature?

**Comment by derfurkan** [comment]
Hi I wonder how this is going?
