### ISSUE TITLE
GitHub links don’t open in the native GitHub iOS app

### ISSUE THREAD

**Issue by mcmxcdev** [ProtonMail/ios-mail#61]
**Describe the bug:**
GitHub links in emails don’t open in native GitHub iOS app but inside Brave browser (default).

**Live App Version:**
4.1.1 (7303)

**Device + OS version**
iPhone with iOS 16.1.1.

**Can you reproduce the problem each time?**
Yes

**Steps to reproduce the behavior:**
1. Receive GitHub notifications in ProtonMail 
2. Click on either "View it on GitHub" or "unsubscribe" link
3. Expect to open inside native GitHub iOS app
4. Actually opens the link inside the browser which is set as default

**Expected behavior**
I would expect ProtonMail to detect that I have the [GitHub app](https://apps.apple.com/us/app/github/id1477376905/) installed and open links there, which has a better user experience and responsiveness compared to the mobile web version.

**Screenshots(If applicable)**

![Screenshot from 2022-12-03 13-23-09](https://user-images.githubusercontent.com/16797721/205440817-72aff333-1173-4fac-a3f7-aeba2bf90036.png)

**Comment by dbanty** [comment]
As a workaround, I've been pressing and holding on the link to get a preview, then clicking the "open link" button (with a Safari icon on it) which opens it in the native GitHub app.

**Comment by mcmxcdev** [comment]
That does indeed work as a workaround, thanks so much!

**Comment by mcmxcdev** [comment]
I have just downloaded the GitHub app again and this issue seems to be resolved now.
